Support npm-style requires
gfredericks/how-to-ns pull request #12
Opened 2019-04-20 02:44 UTC by vemv

Fixes #11

As the test expresses, I went for this kind of sorting:

```clojure
(ns foo
  (:require
   [abc]
   ["foo" :as bar]
   [goofy]))
```

i.e. this sorting doesn't leave all "npm requires" at the bottom:

```clojure
(ns foo
  (:require
   [abc]
   [goofy]
   ["foo" :as bar]))
```

Personally I would tend to care about names (`foo`, `abc`) more than provenance. The alternative seems perfectly reasonable though.

---

An interesting related read:

https://code.thheller.com/blog/shadow-cljs/2019/03/01/what-shadow-cljs-is-and-isnt.html

> ...people mistakenly think that (:require ["foo/bar" :as x]) is something shadow-cljs specific when it is absolutely not.

Cheers - V

2019-04-20 13:08 UTC, gfredericks commented
w.r.t. sorting, if you wanted to you could add an option to switch to the other behavior; I can definitely imagine people appreciating the visual consistency of putting the strings at the bottom.

2019-04-27 00:56 UTC, vemv commented
Fair enough, done!

2019-04-28 23:08 UTC, gfredericks requested changes
This looks good, I would just change the one thing in the sort function, and then I think I'd prefer the option named `:sort-string-requires-to-end?`.

After that I can merge.

2019-04-28 23:08 UTC, gfredericks commented on how-to-ns/src/com/gfredericks/how_to_ns.clj
> +        criterion))))
something like this should avoid the theoretical edge case:

``` clojure
(if place-string-requires-at-bottom?
  [(if (string? namespace) 1 0) criterion]
  criterion)
```

2019-05-20 15:35 UTC, vemv commented
Hey there,

thanks for the review.

Feedback applied!

2019-05-26 23:03 UTC, merged

2019-05-26 23:37 UTC, gfredericks commented
Released as `0.2.5`, thanks again.