Add argument to make cursive-style indentation
gfredericks/how-to-ns pull request #21
Opened 2024-02-09 22:11 UTC by velios

> if two spaces should be used instead, unless the first thing in the list (not counting metadata) is a data structure literal. This should replicate Cursive's default behaviour.

Quote from cljfmt [readme](https://github.com/weavejester/cljfmt). The current behavior breaks the indentation that [Cursive](https://cursive-ide.com/) sets by default. For those teams that work primarily with cursive and idea (like the company I work for), this would be a good help to be able to integrate your amazing tool into their workflow.

2024-02-10 20:27 UTC, gfredericks requested changes
Thanks! I'd be happy to merge this if you could add an example to the existing tests.

2024-02-10 20:27 UTC, gfredericks commented on README.md
> + ;; Only work with :traditional-newline-style? set to false
```suggestion
 ;; if `true` make `(:require\n  <add-one-more-space-symbol-here>[clojure.string :as ...`
 ;; This option only has effect with `:traditional-newline-style?` set to false
```

2024-02-10 22:09 UTC, velios commented
@gfredericks Sure, thx for quick response. I added the necessary tests. Let me know if anything else is need.

2024-02-11 21:20 UTC, merged

2024-02-11 21:30 UTC, gfredericks commented
Released as `0.2.10`.